#!/usr/bin/env bash
# Configure domain zone so that the subdomain www points to your load-balancer IP (lb-01)

print_info(){
    local domain
    local subdomain
    local r_type
    local dest

    domain="$1"
    subdomain="$2"
    r_type="$(dig +short -t CNAME "$subdomain.$domain" 2>/dev/null)"
    dest="$(dig +short "$subdomain.$domain" | tr '\n' ' ')"

    echo "The subdomain $subdomain is a $r_type record that points to $dest"
}
   
# display info for default subdomain

display_default(){
    local domain="$1"
    print_info "$domain" "www"
    print_info "$domain" "lb-01"
    print_info "$domain" "web-01"
    print_info "$domain" "web-02"
}

# logic

if [ "$#" -eq 0 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

domain="$1"

if [ "$#" -eq 1 ]; then
    display_default "$domain"
elif [ "$#" -eq 2 ]; then
    subdomain="$2"
    print_info "$domain" "$subdomain"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
