#!/usr/bin/env bash
# Transfer a file to a server

error_msg="Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
   
# assign paratmeters to variables
PATH_TO_FILE="$1"
SERVER="$2"
USER="$3"
SSH_KEY="$4"

if [ "$SSH_KEY" ]; then
    scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USER@$SERVER:~"
elif [ "$USER" ]; then
    scp -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USER@$SERVER:~"
else
    echo "$error_msg"
    exit 1
fi
