#!/usr/bin/env bash
# Install load balancer


load_balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    timeout client 30s
    timeout connect 5s
    timeout server 30s
    default_backend webservers

backend webservers
    balance roundrobin
    timeout client 30s
    timeout connect 5s
    timeout server 30s
    option forwardfor
    server 243845-web-01 35.175.130.253 check
    server 243845-web-02 54.85.142.216 check
"

# Update
sudo apt-get -y update
sudo apt-get -y upgrade

# HAProxy installation
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.5
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.original}
echo "$load_balancer" > /etc/haproxy/haproxy.cfg

# Restart HAProxy
sudo service haproxy restart
