#!/usr/bin/env bash
# creates a file containing its PID
#   and displays to infinity and beyond indefinitely
#   and displays i hate the kill command when receiving a SIGTERM signal
#   and displays Y U no love me?! when receiving a SIGINT signal
#   and deletes the file generated when receiving a SIGQUIT or SIGTERM signal

trap "echo Y U no love me?!" SIGINT
trap "echo I hate the kill command; rm /var/run/myscript.pid; exit" SIGTERM SIGQUIT

echo $$ > /var/run/myscript.pid

while true
do
    echo "To infinity and beyond"
    sleep 2
done
