#!/usr/bin/env bash
# displays To infinity and beyond indefinitely
#   with a sleep 2 in between each iteration
#   I am Invincible!!! when receiving a SIGTERM signal

trap "echo I am Invincible!!!" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
