#!/usr/bin/env bash
# displays FizzBuzz for multiples of 3 and 5,
#    Fizz for multiples of 3, 
#    Buzz for multiples of 5, and the number for the rest.

x=1
while [ $x -lt 101 ]
do
    if [ $((x % 3)) -eq 0 ] && [ $((x % 5)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((x % 3)) -eq 0 ]
    then
        echo "Fizz"
    elif [ $((x % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo $x
    fi
    ((x++))
done
