#!/usr/bin/bash
# password  story

while IFS=: read -r line;
do
    user=$(echo "$line" | cut -d':' -f1)
    pass=$(echo "$line" | cut -d':' -f2)
    userid=$(echo "$line" | cut -d':' -f3)
    dir=$(echo "$line" | cut -d':' -f6)
    groupid=$(echo "$line" | cut -d':' -f4)
    shell=$(echo "$line" | cut -d':' -f7)
    information=$(echo "$line" | cut -d':' -f5)

    echo "The user $user is part of the $groupid gang, lives in $dir and rides $shell. $userid's place is protected by the passcode $pass, more info about the user here: $information"    
done < /etc/passwd