#!/usr/bin/env bash
# Displays bad luck for the 4th iteration
#   Displays good luck for the 8th iteration
#   Displays Best School for the other iterations   

x=10
while [ $x -gt 0 ]
do
    if [ $x -eq 7 ]
    then
        echo "bad luck"
    elif [ $x -eq 3 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((x--))
done
