#!/usr/bin/env bash
# Displays 4 then bad luck from China the 4th iteration
#   Displays 9 then bad luck from Japan the 9th iteration
#   Displays 17 then bad luck from Italy the 17th iteration

x=1
while [ $x -le 20 ]
do
    echo "$x"
    case $x in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
    esac
    ((x++))
done
