#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirements.
# Requirements:
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8

cp /etc/hosts /tmp/hosts
sed -i s/^127.*/"127.0.0.2 localhost"/ /tmp/hosts
echo "8.8.8.8 facebook.com" >> /tmp/hosts
sudo cp /tmp/hosts /etc/hosts
